config/routes.rb
Rails.application.routes.draw do
  resources :drinks, except: %i[show destroy]

  resources :clients, except: %i[destroy] do
    member do
      patch :suspend
      patch :reinstate
    end
    resources :payments, only: %i[create]
  end

  namespace :external do
    resources :client, param: :access_uuid, only: %i[show] do
      resources :monthly_reports, only: %i[show]
    end
  end

  resources :payments, only: %i[index]

  resources :orders, except: %i[show destroy] do
    resources :positions, controller: "order_positions", except: %i[index show destroy]
  end

  resources :monthly_reports, except: %i[show destroy] do
    member do
      patch :complete_settlements
    end
  end

  resources :settlements, except: %i[show] do
    collection do
      get "filtered/:client_id", to: "settlements#filtered", as: :filtered
    end

    member do
      patch :complete
      patch :schedule_email
    end

    resources :positions, controller: "settlement_positions", except: %i[index show]
  end

  resources :settlement_prices, except: %i[show destroy] do
    patch :deactivate, on: :member
  end

  resources :leaderboards, only: %i[index]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "inventory#show"
end

app/models/settlement.rb
class Settlement < ApplicationRecord
  include AASM

  belongs_to :client
  belongs_to :monthly_report
  belongs_to :payment, optional: true
  has_many :positions, class_name: "SettlementPosition", dependent: :destroy

  scope :newest_first, -> { order(generated_at: :desc) }

  validates :generated_at, presence: true

  with_options on: :email_delivery do
    validates :email_sent_at, absence: true
    validate :client_must_have_email
  end

  aasm do
    state :draft, initial: true
    state :completed
    state :paid

    event :complete, after: %(set_completed_at) do
      transitions from: :draft, to: :completed
    end

    event :mark_paid, after: :set_paid_at do
      transitions from: :completed, to: :paid
    end
  end

  def price_in_cents
    positions.sum(:price_in_cents)
  end

  def schedule_email_delivery
    return false unless valid?(:email_delivery)

    SettlementMailer.with(settlement: self).completed_mail.deliver_later
    update(email_sent_at: Time.current)
  end

  private

  def client_must_have_email
    return true if client.email.present?

    errors.add(:base, "Client must have an email address")
  end

  def set_completed_at
    self.completed_at ||= Time.current
  end

  def set_paid_at
    self.paid_at ||= Time.current
  end
end

app/controllers/settlements_controller.rb
class SettlementsController < ApplicationController
  before_action :set_settlement, only: %i[ edit update destroy complete schedule_email ]

  def index
    @settlements = Settlement.includes(:client, :monthly_report).newest_first.all
  end

  def filtered
    @client = Client.find(params[:client_id])
    @settlements = Settlement.where(client: @client).newest_first.all
  end

  def new
    @settlement = Settlement.new(
      {
        generated_at: Time.current,
        monthly_report_id: params[:monthly_report_id],
        client_id: params[:client_id]
      }.compact_blank
    )
  end

  def edit
  end

  def create
    @settlement = Settlement.new(settlement_params)

    if @settlement.save
      redirect_to edit_settlement_path(@settlement)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @settlement.update(settlement_params)
      redirect_to edit_settlement_path(@settlement)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def complete
    @settlement.complete!
    redirect_to settlements_path
  end

  def schedule_email
    if @settlement.schedule_email_delivery
      flash[:notice] = "Email sent."
    end

    redirect_back_or_to settlements_path
  end

  def destroy
    if @settlement.draft?
      @settlement.destroy!
    end

    redirect_to settlements_path
  end

  private

  def set_settlement
    @settlement = Settlement.find(params.expect(:id))
  end

  def settlement_params
    params.expect(settlement: [ :client_id, :generated_at, :paid_at, :monthly_report_id ])
  end
end

app/views/settlements/_form.html.slim
= simple_form_for settlement do |form|
  fieldset disabled=!settlement.draft?
    = form.input :client_id, collection: Client.all, include_blank: false
    = form.input :monthly_report_id, collection: MonthlyReport.all, include_blank: false
    = form.input :generated_at, html5: true
    = form.button :submit

- if settlement.persisted?
  h2 Positions

  table#positions
    thead
      th Drink
      th Amount
      th Price
      th Actions
    tbody
      - settlement.positions.each do |position|
        tr
          td= link_to position.drink.name, edit_settlement_position_path(position.settlement, position)
          td= position.amount
          td= formatted_price(position.price_in_cents)
          td
            - if settlement.draft?
              = button_to "Delete", settlement_position_path(position.settlement, position), method: :delete, data: { turbo_confirm: "Sure?" }
      tr
        td
        td
        td: strong= formatted_price(settlement.price_in_cents)

- if settlement.persisted? && settlement.draft?
  = button_to "Complete Settlement", complete_settlement_path(settlement), method: :patch, data: { turbo_confirm: "Sure?" }

- if settlement.persisted?
  .settlement-form
    - if settlement.draft?
      .settlement-form__new-position
        h2 Add Position

        = render "settlement_positions/form", settlement: @settlement, position: @position

    - if settlement.monthly_report.present?
      .settlement-form__monthly-report-image
        = link_to "Back to the Report", edit_monthly_report_path(settlement.monthly_report)

        = image_tag settlement.monthly_report.image.url

app/views/settlements/_table.html.slim
table#settlements
  thead
    th Client
    th Price
    th State
    th Generated At
    th Completed At
    th Paid At
    th Email Sent At
    th Actions
  tbody
    - settlements.group_by { |record| record.generated_at }.each do |date, settlements|
      - monthly_report = settlements.first.monthly_report
      tr
        td colspan="8" style="background-color: #ededed;"
          = link_to "#{monthly_report.title} (#{l(date)})", edit_monthly_report_path(monthly_report)
      - settlements.each do |settlement|
        tr
          td
            = link_to settlement.client.name, edit_client_path(settlement.client)
            |&nbsp;
            span= link_to "🔍", filtered_settlements_path(client_id: settlement.client_id)
          td= link_to formatted_price(settlement.price_in_cents), edit_settlement_path(settlement)
          td= settlement.aasm_state
          td= formatted_date(settlement.generated_at)
          td= formatted_date(settlement.completed_at)
          td= formatted_date(settlement.paid_at)
          td= formatted_date(settlement.email_sent_at)
          td
            - if settlement.draft?
              = button_to "Delete", settlement_path(settlement), method: :delete, data: { turbo_confirm: "Sure?" }
            - else
              - if settlement.valid?(:email_delivery)
                = button_to "Send Mail", schedule_email_settlement_path(settlement), method: :patch, data: { turbo_confirm: "Sure?" }

app/views/settlements/edit.html.slim
h1 Settlement

= render "form", settlement: @settlement

app/views/settlements/filtered.html.slim
h1 Settlements for #{@client.name}

= render "table", settlements: @settlements

app/views/settlements/index.html.slim
h1 Settlements

= link_to "New settlement", new_settlement_path
= render "table", settlements: @settlements

app/views/settlements/new.html.slim
h1 New settlement

= render "form", settlement: @settlement