config/routes.rb
Rails.application.routes.draw do
  resources :drinks, except: %i[show destroy]

  resources :clients, except: %i[destroy] do
    member do
      patch :suspend
      patch :reinstate
    end
    resources :payments, only: %i[create]
  end

  namespace :external do
    resources :client, param: :access_uuid, only: %i[show] do
      resources :monthly_reports, only: %i[show]
    end
  end

  resources :payments, only: %i[index]

  resources :orders, except: %i[show destroy] do
    resources :positions, controller: "order_positions", except: %i[index show destroy]
  end

  resources :monthly_reports, except: %i[show destroy] do
    member do
      patch :complete_settlements
    end
  end

  resources :settlements, except: %i[show] do
    collection do
      get "filtered/:client_id", to: "settlements#filtered", as: :filtered
    end

    member do
      patch :complete
      patch :schedule_email
    end

    resources :positions, controller: "settlement_positions", except: %i[index show]
  end

  resources :settlement_prices, except: %i[show destroy] do
    patch :deactivate, on: :member
  end

  resources :leaderboards, only: %i[index]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "inventory#show"
end

app/models/settlement_price.rb
class SettlementPrice < ApplicationRecord
  belongs_to :drink

  validates :valid_from, presence: true
  validates :price_in_cents, presence: true, numericality: true

  scope :active, -> { where(deactivated_at: nil) }

  def deactivate
    update(deactivated_at: Time.current)
  end
end

app/controllers/settlement_prices_controller.rb
class SettlementPricesController < ApplicationController
  before_action :set_price, only: %i[ edit update deactivate ]

  def index
    @prices = SettlementPrice.active
  end

  def new
    @price = SettlementPrice.new(valid_from: Time.current)
  end

  def edit
  end

  def create
    @price = SettlementPrice.new(price_params)

    if @price.save
      redirect_to settlement_prices_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @price.update(price_params)
      redirect_to settlement_prices_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def deactivate
    @price.deactivate
    redirect_to settlement_prices_path
  end

  private

  def set_price
    @price = SettlementPrice.find(params.expect(:id))
  end

  def price_params
    params.expect(settlement_price: [ :drink_id, :price_in_cents, :valid_from ])
  end
end

app/views/settlement_prices/_form.html.slim
= simple_form_for price do |form|
  = form.input :drink_id, collection: (Drink.all - SettlementPrice.active.map(&:drink)), include_blank: false
  = form.input :price_in_cents
  = form.input :valid_from, html5: true
  = form.button :submit

app/views/settlement_prices/edit.html.slim
h1 Editing Price

= render "form", price: @price

app/views/settlement_prices/index.html.slim
h1 Prices

= link_to "New Price", new_settlement_price_path

table#settlements
  thead
    th Drink
    th Price
    th Valid from
    th Actions
  tbody
    - @prices.each do |price|
      tr
        td= price.drink.name
        td= link_to formatted_price(price.price_in_cents), edit_settlement_price_path(price)
        td= l(price.valid_from, format: :short)
        td= button_to "Deactivate", deactivate_settlement_price_path(price), method: :patch, data: { turbo_confirm: "Sure?" }

app/views/settlement_prices/new.html.slim
h1 New Price

= render "form", price: @price