config/routes.rb
Rails.application.routes.draw do
  resources :drinks, except: %i[show destroy]

  resources :clients, except: %i[destroy] do
    member do
      patch :suspend
      patch :reinstate
    end
    resources :payments, only: %i[create]
  end

  namespace :external do
    resources :client, param: :access_uuid, only: %i[show] do
      resources :monthly_reports, only: %i[show]
    end
  end

  resources :payments, only: %i[index]

  resources :orders, except: %i[show destroy] do
    resources :positions, controller: "order_positions", except: %i[index show destroy]
  end

  resources :monthly_reports, except: %i[show destroy] do
    member do
      patch :complete_settlements
    end
  end

  resources :settlements, except: %i[show] do
    collection do
      get "filtered/:client_id", to: "settlements#filtered", as: :filtered
    end

    member do
      patch :complete
      patch :schedule_email
    end

    resources :positions, controller: "settlement_positions", except: %i[index show]
  end

  resources :settlement_prices, except: %i[show destroy] do
    patch :deactivate, on: :member
  end

  resources :leaderboards, only: %i[index]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "inventory#show"
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :settlements, -> { newest_first }
  has_many :payments, -> { newest_first }

  scope :active, -> { where(suspended_at: nil) }
  scope :with_email, -> { where.not(email: nil) }

  before_create :set_access_uuid

  validates :name, presence: true
  validates :email, uniqueness: true, allow_blank: true

  def suspended?
    suspended_at.present?
  end

  def suspend!
    update(suspended_at: Time.current)
  end

  def reinstate!
    update(suspended_at: nil)
  end

  def outstanding_payment_sum_in_cents
    settlements.includes(:positions).completed.sum(&:price_in_cents)
  end

  private

  def set_access_uuid
    self.access_uuid = SecureRandom.uuid
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ edit update suspend reinstate ]

  def index
    @clients = Client.all.order(suspended_at: :asc)
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to clients_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @client.update(client_params)
      redirect_to clients_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def suspend
    @client.suspend!
    redirect_to clients_path
  end

  def reinstate
    @client.reinstate!
    redirect_to clients_path
  end

  private

  def set_client
    @client = Client.find(params.expect(:id))
  end

  def client_params
    params.expect(client: [ :name, :email ]).compact_blank
  end
end

app/controllers/external/client_controller.rb
class External::ClientController < External::BaseController
  def show
    @client = Client.find_by!(access_uuid: params[:access_uuid])
  end
end

app/views/clients/_form.html.slim
= simple_form_for client do |form|
  = form.input :name
  = form.input :email, as: :email
  = form.button :submit

app/views/clients/edit.html.slim
h1 Editing Client

= render "form", client: @client

app/views/clients/index.html.slim
ruby:
  settlements_total = Hash.new(0)

h1 Clients

= link_to "New Client", new_client_path

table#clients
  thead
    th Name
    th E-Mail
    th Outstanding
    th Paid
    th Create Payment
    th Other
  tbody
    - @clients.each do |client|
      ruby:
        outstanding = client.outstanding_payment_sum_in_cents
        paid = client.settlements.paid.sum(&:price_in_cents)
        settlements_total[:outstanding] += outstanding
        settlements_total[:paid] += paid
      tr class="#{client.suspended? ? 'text-muted' : ''}"
        td
          = client.name
          - if client.suspended?
            |  (Suspended)
        td= client.email
        td: strong = formatted_price(outstanding)
        td= formatted_price(paid)
        td
          - if outstanding.positive?
            | &nbsp;
            = link_to "Create Payment", client_payments_path(client_id: client.id), data: { turbo_method: :post, turbo_confirm: "Sure?" }
        td
          - if client.access_uuid?
            = link_to "External", external_client_url(client.access_uuid)
            | &nbsp;
          = link_to "Edit", edit_client_path(client)
          | &nbsp;
          = link_to "Settlements", filtered_settlements_path(client_id: client.id)
          | &nbsp;
          - if client.suspended?
            = link_to "Reinstate", reinstate_client_path(client), data: { turbo_method: :patch }
          - else
            = link_to "Suspend", suspend_client_path(client), data: { turbo_method: :patch }

  tfoot
    tr
      th Totals
      td
      td: strong = formatted_price(settlements_total[:outstanding])
      td = formatted_price(settlements_total[:paid])
      th

app/views/clients/new.html.slim
h1 New client

= render "form", client: @client