config/routes.rb
Rails.application.routes.draw do
  resources :drinks, except: %i[show destroy]

  resources :clients, except: %i[destroy] do
    member do
      patch :suspend
      patch :reinstate
    end
    resources :payments, only: %i[create]
  end

  namespace :external do
    resources :client, param: :access_uuid, only: %i[show] do
      resources :monthly_reports, only: %i[show]
    end
  end

  resources :payments, only: %i[index]

  resources :orders, except: %i[show destroy] do
    resources :positions, controller: "order_positions", except: %i[index show destroy]
  end

  resources :monthly_reports, except: %i[show destroy] do
    member do
      patch :complete_settlements
    end
  end

  resources :settlements, except: %i[show] do
    collection do
      get "filtered/:client_id", to: "settlements#filtered", as: :filtered
    end

    member do
      patch :complete
      patch :schedule_email
    end

    resources :positions, controller: "settlement_positions", except: %i[index show]
  end

  resources :settlement_prices, except: %i[show destroy] do
    patch :deactivate, on: :member
  end

  resources :leaderboards, only: %i[index]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "inventory#show"
end

app/models/monthly_report.rb
class MonthlyReport < ApplicationRecord
  has_many :settlements
  has_one_attached :image

  def overall_amount
    settlements.flat_map(&:positions).sum(&:amount)
  end

  def complete_settlements!
    settlements.draft.find_each do |settlement|
      settlement.complete!
    end
  end
end

app/controllers/external/monthly_reports_controller.rb
class External::MonthlyReportsController < External::BaseController
  def show
    @client = Client.find_by!(access_uuid: params[:client_access_uuid])
    @report = MonthlyReport.find(params[:id])
  end
end

app/controllers/monthly_reports_controller.rb
class MonthlyReportsController < ApplicationController
  before_action :set_monthly_report, only: %i[ edit update complete_settlements ]

  def index
    @monthly_reports = MonthlyReport.order(id: :desc).all
  end

  def new
    @monthly_report = MonthlyReport.new
  end

  def edit
    @settlements = @monthly_report.settlements.includes(:client)
    settled_clients = @settlements.map(&:client)
    @clients = Client.active - settled_clients
  end

  def create
    @monthly_report = MonthlyReport.new(monthly_report_params)

    if @monthly_report.save
      redirect_to monthly_reports_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @monthly_report.update(monthly_report_params)
      redirect_to monthly_reports_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def complete_settlements
    @monthly_report.complete_settlements!

    redirect_back fallback_location: edit_monthly_report_path(@monthly_report)
  end

  private

  def set_monthly_report
    @monthly_report = MonthlyReport.find(params.expect(:id))
  end

  def monthly_report_params
    params.expect(monthly_report: [ :title, :description, :image ])
  end
end

app/views/monthly_reports/_form.html.slim
.monthly-report-form
  = simple_form_for monthly_report do |form|
    = form.input :title, as: :string
    = form.input :description, as: :text
    - if form.object.image.attached?
      = image_tag form.object.image.url
    = form.input :image
    = form.button :submit

  - if monthly_report.persisted?
    section.report-clients
      h3 To be settled
      ul
        - @clients.each do |client|
          li= link_to client.name, new_settlement_path(client_id: client.id, monthly_report_id: monthly_report.id)

      h3 Settled (#{@settlements.size})
      ul
        - @settlements.each do |settlement|
          li= link_to settlement.client.name, edit_settlement_path(settlement)

      h3 Overall Amount (#{monthly_report.overall_amount})

      = button_to "Mark as completed", complete_settlements_monthly_report_path(monthly_report), method: :patch, data: { turbo_confirm: "Sure?" }

app/views/monthly_reports/edit.html.slim
h1 Editing Report

= render "form", monthly_report: @monthly_report

app/views/monthly_reports/index.html.slim
h1 Monthly Reports

= link_to "New Report", new_monthly_report_path

table#monthly_reports
  thead
    th Title
  tbody
    - @monthly_reports.each do |report|
      tr
        td= link_to report.title, edit_monthly_report_path(report)

app/views/monthly_reports/new.html.slim
h1 New Report

= render "form", monthly_report: @monthly_report